CREATE SCHEMA INFO;
CREATE table INFO.STUDENTS(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    age INT,
    major VARCHAR(50),
    gpa NUMERIC(3,2)
);

INSERT INTO  INFO.STUDENTS (name, age, major, gpa) VALUES
  ('An', 20, 'CNTT', 3.5),
  ('Bình', 21, 'Toán', 3.2),
  ('Cường', 22, 'CNTT', 3.8),
  ('Dương', 20, 'Vật Lý', 3.0),
  ('Em', 21, 'CNTT', 2.9);

INSERT INTO INFO.STUDENTS (name, age, major, gpa) VALUES
  ('Hùng', 23, 'Hoá Học', 3.4);

UPDATE INFO.STUDENTS SET gpa = 3.6 WHERE id = 2;

DELETE FROM INFO.STUDENTS WHERE gpa < 3.0;

SELECT * FROM INFO.STUDENTS ORDER BY gpa DESC;

SELECT DISTINCT name FROM INFO.STUDENTS WHERE major = 'CNTT' LIMIT 1;

SELECT * FROM INFO.STUDENTS WHERE gpa BETWEEN 3.0 AND 3.6;

SELECT * FROM INFO.STUDENTS WHERE name ILIKE 'C%';

SELECT * FROM INFO.STUDENTS ORDER BY name LIMIT 3;

SELECT * FROM INFO.STUDENTS ORDER BY name LIMIT 3 OFFSET 4